// <auto-generated/>
using KiotaWebApi.Client.Api.Categories.Image.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaWebApi.Client.Api.Categories.Image {
    /// <summary>
    /// Builds and executes requests for operations under \api\categories\image
    /// </summary>
    public class ImageRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the KiotaWebApi.Client.api.categories.image.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithImageItemRequestBuilder this[int position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("imageId", position);
            return new WithImageItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>Gets an item from the KiotaWebApi.Client.api.categories.image.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public WithImageItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("imageId", position);
            return new WithImageItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new ImageRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/categories/image", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new ImageRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/categories/image", rawUrl) {
        }
    }
}
